INSTITUTION_TYPE = (
    ('HPG', 'Hospital Geral'),
    ('HED', 'Hospital Especializado'),
        ('HCG',' Hospital de Cardiologia'),
        ('HOG', 'Hospital de Oncologia '),
        ('HPC',' Hospital Psiquiátrico'),
        ('HTP', 'Hospital Ortopédico'),
        ('HPA', 'Hospital Pediátrico'),
        ('HFG', 'Hospital Oftalmológico'),
        ('HNG', 'Hospital de Neurologia'),
        ('HUT', 'Hospital Universitário '),
        ('HRB', 'Hospital de Reabilitação'),
        ('HUE', 'Hospital de Urgência e Emergência'),
        ('HMD', 'Hospital Maternidade'),
        ('HCA', 'Hospital de Cirurgia'),
        ('HDI', 'Hospital de Doenças Infecciosas'),
    ('HMT', 'Hospital Militar'),
    ('HCT', 'Hospital Comunitário'),
    ('HLP', 'Hospital de Longa Permanência'),
    ('CGL', 'Clínica Geral'),
    ('CED', 'Clínica Especializada'),
        ('CCG', 'Clínica de Cardiologia:'),
        ('CDG', 'Clínica de Dermatologia:'),
        ('CGO', 'Clínica de Ginecologia e Obstetrícia'),
        ('COP', 'Clínica de Ortopedia'),
        ('CPT', 'Clínica de Pediatria'),
        ('CNG', 'Clínica de Neurologia'),
        ('COG', 'Clínica de Oftalmologia'),
        ('CEG', 'Clínica de Endocrinologia'),
        ('CPQ', 'Clínica de Psiquiatria'),
    ('CTG', 'Clínica Odontológica'),
    ('CFP', 'Clínica de Fisioterapia'),
    ('CET', 'Clínica de Estética'),
    ('CIM', 'Clínica de Imagem'),
    ('CMT', 'Clínica de Medicina do Trabalho'),
    ('CFD', 'Clínica de Fertilidade'),
    ('CRB', 'Clínica de Reabilitação'),
    ('CHS', 'Clínica de Hemodiálise'),
    ('COA', 'Clínica de Oncologia'),
    ('CVT', 'Clínica Veterinária'),
    ('CPL', 'Clínica Popular'),
)

PHONE_TYPES = (
    ('TFP', 'Telefone Principal'),
    ('TFE', 'Telefone de Emergência'),
    ('TFR', 'Telefone de Recepção'),
    ('TAP', 'Telefone de Atendimento ao Paciente'),
    ('TFC', 'Telefone de Consultório'),
    ('TUI', 'Telefone de Unidade de Internação'),
    ('TFL', 'Telefone de Laboratório'),
    ('TFF', 'Telefone de Farmácia'),
    ('TFA', 'Telefone de Administração'),
    ('TRH', 'Telefone de Departamento de Recursos Humanos'),
    ('TST', 'Telefone de Suporte Técnico'),
)